export const LOGOUT = "LOGOUT";
export const SIGNIN = "SIGNIN";
export const SIGNUP = "SIGNUP";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const EMAIL_CONFIRMATION = "EMAIL_CONFIRMATION";

export const GET_ALL_COURSE = "GET_ALL_COURSE";
export const ADD_COURSE = "ADD_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const UPDATE_COURSE_BY_ID = "UPDATE_COURSE_BY_ID";

export const GET_ALL_STUDENT = "GET_ALL_STUDENT";
export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const UPDATE_STUDENT_BY_ID = "UPDATE_STUDENT_BY_ID";
export const MARK_ATTENDANCE = "MARK_ATTENDANCE";
